php neosentry.php collect -a configuration -d "216.227.89.53" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.38.56.249" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.38.56.246" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.38.56.221" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.50.56.249" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.38.190.214" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.16.28.251" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.38.163.241" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.132.129.151" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "207.230.208.226" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.51.223.252" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.38.191.75" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.50.68.254" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.208.99.178" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.38.191.107" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.38.106.245" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.51.49.18" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.51.50.250" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.51.150.253" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.51.49.182" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.51.149.218" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.51.18.35" --config-script "checkpoint.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"


echo
echo "processing palo alto devices"

php neosentry.php collect -a configuration -d "10.32.224.70" --config-script "paloalto.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.38.158.233" --config-script "paloalto.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.38.26.225" --config-script "paloalto.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.59.31.10" --config-script "paloalto.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.47.56.248" --config-script "paloalto.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.47.56.247" --config-script "paloalto.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.38.135.117" --config-script "paloalto.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.38.85.230" --config-script "paloalto.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.51.71.252" --config-script "paloalto.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.50.102.90" --config-script "paloalto.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.50.64.248" --config-script "paloalto.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"
php neosentry.php collect -a configuration -d "10.50.64.210" --config-script "paloalto.php" --config-profile "{\"username\": \"fwadmin\", \"password\": \"1^<3@n0v3mb3rm00n#\" }"

